
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-mysql
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    name: mysql-source-connector
    tasks.max: 1
    database.hostname: mysql-master
    database.port: 3306
    database.user: root
    database.password: rootpw
    database.server.id: 1
    database.dbname: mydatabase
    topic.prefix: original
    snapshot.mode: initial
    schema.history.internal.kafka.topic: original.history 
    database.include.list: mydatabase
    schema.history.internal.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: original.history
    quote.identifiers: true
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mysql-source-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    name: mysql-source-connector
    connector.class: io.debezium.connector.mysql.MySqlConnector

    # Database connection configuration
    database.hostname: mysql-master
    database.port: 3306
    database.user: root
    database.password: rootpw
    database.server.id: 1
    database.server.name: mysql-master
    database.dbname: mydatabase
    database.include.list: mydatabase

    # exclude tables and columns
    table.exclude.list: mydatabase.customer_info
    column.exclude.list: mydatabase.subscriber_data.email,mydatabase.subscriber_data.credit_card

    # Kafka connection configuration
    schema.history.internal.kafka.bootstrap.servers:  my-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: schemahistory.history
    topic.prefix: history.history

    # Transformation configuration
    transforms: unwrap,dropPrefix,maskCC
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: true
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.dropPrefix.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.dropPrefix.regex: history.history.mydatabase.(.*)
    transforms.dropPrefix.replacement: replica_$1
    transforms.maskCC.type: org.apache.kafka.connect.transforms.MaskField$Value
    transforms.maskCC.fields: city,country,email,credit_card
    transforms.maskCC.replacement: XXXX-XXXX-XXXX-XXXX

    # Error handling configuration
    event.deserialization.failure.handling.mode: warn
    event.processing.failure.handling.mode: warn
    inconsistent.schema.handling.mode: warn
    errors.max.retries: 1000000000

    # Other configuration
    tasks.max: 1
    include.schema.changes: true
    include.schema.comments: true
    quote.identifiers: true
    poll.interval.ms: 10000
    batch.max.rows: 250000
    datatype.propagate.source.type: .*
    column.propagate.source.type: .*
    connect.keep.alive: true
    include.query: true
    snapshot.mode: initial

    # Predicates configuration
    predicates: isTombstone
    predicates.isTombstone.type: org.apache.kafka.connect.transforms.predicates.RecordIsTombstone
    transforms.x.negate: true
    transforms.x.predicate: isTombstone
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mysql-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    name: mysql-sink-connector
    connector.class: io.confluent.connect.jdbc.JdbcSinkConnector

    # Database connection configuration
    connection.url: jdbc:mysql://mysql-replica:3306/mydatabase
    connection.user: root
    connection.password: rootpw
    connection.pool.timeout: 1800

    # Kafka connection configuration
    topics.regex: replica_(.*)
    schema.history.internal.kafka.topic: schemahistory.history

    # Transformation configuration
    transforms: dropPrefix
    transforms.dropPrefix.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.dropPrefix.regex: replica_(.*)
    transforms.dropPrefix.replacement: $1

    # Schema handling configuration
    quote.identifiers: true
    include.schema.changes: true
    schema.evolution: basic
    auto.evolve: true
    include.schema.comments: true

    # Record handling configuration
    insert.mode: upsert
    table.name.format: ${topic}
    primary.key.mode: record_key
    pk.mode: record_key
    pk.fields: ""
    delete.enabled: true

    # Error handling configuration
    event.deserialization.failure.handling.mode: warn
    inconsistent.schema.handling.mode: warn

    # Other configuration
    tasks.max: 1
    group.id: 1
    auto.create: true
    include.query: true
    name: mysql-sink-connector
