apiVersion: v1
kind: Service
metadata:
  name: my-connect-cluster-external
  namespace: kafka
  labels:
    strimzi.io/cluster: my-connect-cluster
    strimzi.io/kind: KafkaConnect
    strimzi.io/name: my-connect-cluster-connect
spec:
  type: LoadBalancer
  selector:
    strimzi.io/cluster: my-connect-cluster
    strimzi.io/kind: KafkaConnect
    strimzi.io/name: my-connect-cluster-connect
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8083
